version: "3.7"

services:
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    restart: always
  
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080
    restart: always