version: "3.7"

services:
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    environment:
      PORT: 5000
    restart: always
  
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080
    environment:
      VUE_APP_API_URL: http://localhost
      VUE_APP_API_PORT: 5000
    restart: always