version: "3.7"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/src:/backend/src
    ports:
      - 5000:5000
    environment:
      PORT: 5000
  
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - 8080:8080
    environment:
      VUE_APP_API_URL: http://localhost
      VUE_APP_API_PORT: 5000
      CHOKIDAR_USEPOLLING: "true"